In [170]:
import numpy as np

In [171]:
# numpy can be seeded either on global level...

np.random.seed(17)
print(np.random.randn(5))
print(np.random.randn(5))

[ 0.27626589 -1.85462808  0.62390111  1.14531129  1.03719047]
[ 1.88663893 -0.11169829 -0.36210134  0.14867505 -0.43778315]


In [172]:
# ... or on the level of an object

reandseed1 = np.random.RandomState(17)
reandseed2 = np.random.RandomState(20210530)

print(reandseed1.rand(5))
print(reandseed2.rand(5))
print(reandseed1.rand(5))
print(reandseed2.rand(5))
print(np.random.rand(5)) # the only output which changes every time the cell is run
# however, the global seed from the first cell is still in effect

[0.294665   0.53058676 0.19152079 0.06790036 0.78698546]
[0.13128311 0.40968431 0.53891849 0.61951919 0.65726249]
[0.65633352 0.6375209  0.57560289 0.03906292 0.3578136 ]
[0.67593914 0.92015352 0.01978739 0.00161252 0.49311545]
[0.55175137 0.59751325 0.48352862 0.28298816 0.29772572]


In [173]:
# PyTorch
import torch

# PyTorch can be seeded only on the global level
torch.manual_seed(17)
print(torch.rand(5))
print(torch.rand(5))

# PyTorch seed does not spread to numpy
print(np.random.rand(5))

tensor([0.4342, 0.5351, 0.8302, 0.1239, 0.0293])
tensor([0.5494, 0.3825, 0.5463, 0.4683, 0.0172])
[0.56150891 0.39604744 0.78870071 0.41848439 0.14390392]
